### ISSUE TITLE
Update storage class "manual" to default in  mariadb-operator/deploy/mariadb_pvc.yaml 

### ISSUE THREAD

**Issue by ghanshyams92** [abalki001/mariadb-operator#9]
Update storage class "manual" to default in  mariadb-operator/deploy/mariadb_pvc.yaml  and mariadb-operator/deploy/mariadb_pv.yaml .
While automating the mariadb operator deployment storage class  type "manual" always goes in Pending state, it should be default. 
![image](https://user-images.githubusercontent.com/35167528/104456805-38889b00-55cf-11eb-84ce-e21107dac680.png)

Please have a look.
Ghanshyam S.

**Comment by abalki001** [comment]
Hi Ghanshyam.
Sorry for the delayed response. I have merged your changes after reviewing.
Thanks for the contribution.

Abhijit.
